# Generated by Django 4.2 on 2023-05-02 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("corpu_employee", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="pre_requisite",
            field=models.ForeignKey(
                blank=True,
                default="",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="corpu_employee.course",
            ),
        ),
    ]
