# Generated by Django 4.2 on 2023-05-02 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("corpu_employee", "0002_alter_course_pre_requisite"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "user_id",
                    models.AutoField(
                        max_length=9, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("first_name", models.CharField(max_length=14)),
                ("last_name", models.CharField(max_length=14)),
                ("email", models.CharField(max_length=29, unique=True)),
                ("contact_no", models.CharField(max_length=14, unique=True)),
                ("user_type", models.CharField(max_length=9)),
                ("password", models.CharField(max_length=19)),
            ],
        ),
        migrations.CreateModel(
            name="UserLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latutude", models.CharField(max_length=19)),
                ("longiture", models.CharField(max_length=19)),
                ("address", models.CharField(max_length=99)),
                (
                    "user_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="corpu_employee.user",
                    ),
                ),
            ],
        ),
    ]
