# Generated by Django 4.2 on 2023-05-10 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corpu_employee", "0005_timetable_assessment_timetable_user_course_timetable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timetable",
            name="friday_time",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="timetable",
            name="monday_time",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="timetable",
            name="thursday_time",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="timetable",
            name="tuesday_time",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="timetable",
            name="wednesday_time",
            field=models.JSONField(null=True),
        ),
    ]
