# Generated by Django 4.2 on 2023-05-16 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corpu_employee", "0007_alter_timetable_course_code_alter_timetable_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="details",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="details",
            field=models.JSONField(null=True),
        ),
    ]
