# Generated by Django 4.2 on 2023-05-25 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("corpu_employee", "0008_assessment_details_user_details"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.CharField(max_length=29)),
                ("status", models.CharField(max_length=9, null=True)),
                (
                    "applicant_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="corpu_employee.user",
                    ),
                ),
                (
                    "course_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="corpu_employee.course",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="jobapplication",
            constraint=models.UniqueConstraint(
                fields=("applicant_id", "course_code"), name="user_course_application"
            ),
        ),
    ]
