# Generated by Django 4.2 on 2023-05-25 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corpu_employee", "0009_jobapplication_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="data",
            field=models.JSONField(null=True),
        ),
    ]
