# Generated by Django 4.2 on 2023-05-02 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "course_code",
                    models.CharField(
                        max_length=9, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("course_title", models.CharField(max_length=99, unique=True)),
                (
                    "pre_requisite",
                    models.CharField(blank=True, default="", max_length=9),
                ),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=499),
                ),
            ],
        ),
    ]
