# Generated by Django 4.2 on 2023-05-02 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "course_code",
                    models.CharField(
                        max_length=9, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("course_title", models.CharField(max_length=99, unique=True)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=499),
                ),
                (
                    "pre_requisite",
                    models.ForeignKey(
                        blank=True,
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="corpu_employee.course",
                    ),
                ),
            ],
        ),
    ]
